---
parser: babel-eslint
parserOptions:
  sourceType: module
plugins:
- prettier
- security
- unicorn
- promise
- istanbul
- jsdoc
- markdown
extends:
- eslint:recommended
- plugin:security/recommended
- plugin:eslint-comments/recommended
- plugin:unicorn/recommended
- plugin:node/recommended
- plugin:import/errors
- plugin:import/warnings
- plugin:jsdoc/recommended
- plugin:md/recommended
- plugin:json/recommended
- standard
- prettier-standard/prettier-file
env:
  browser: false
  node: true
globals:
  Promise: true
rules:
  prettier/prettier: error
  node/shebang:
  - error
  - convertPath:
      bin/**/*.js:
      - "^bin/(.+?)\\.js$"
      - lib/bin/$1.js
  node/no-unsupported-features/es-syntax:
  - error
  - ignores:
    - modules
  istanbul/no-ignore-file: error
  istanbul/prefer-ignore-reason: error
  promise/no-callback-in-promise: 'off'
overrides:
- files:
  - src/test/**
  - cucumber.js
  plugins:
  - chai-friendly
  extends:
  - plugin:chai-friendly/recommended
  globals:
    expect: true
    PendingError: true
  rules:
    security/detect-non-literal-fs-filename: 'off'
    jsdoc/require-jsdoc: 'off'
- files:
  - scripts/**
  parserOptions:
    sourceType: module
    allowImportExportEverywhere: true
  rules:
    node/shebang: 'off'
- files:
  - "*.md"
  parser: markdown-eslint-parser
  rules:
    unicorn/filename-case: 'off'
